# Generated by Django 5.2.7 on 2025-11-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoGiaDinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_ho_khau', models.CharField(max_length=20, unique=True)),
                ('ho_ten_chu_ho', models.CharField(max_length=100)),
                ('so_nha', models.CharField(max_length=50)),
                ('duong_pho', models.CharField(max_length=100)),
                ('phuong_xa', models.CharField(max_length=100)),
                ('quan_huyen', models.CharField(max_length=100)),
                ('ngay_tao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
