# Generated by Django 5.2.7 on 2025-11-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ho_gia_dinh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hogiadinh',
            name='ghi_chu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hogiadinh',
            name='so_dien_thoai',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
