# Generated by Django 5.2.7 on 2025-11-04 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ho_gia_dinh', '0002_hogiadinh_ghi_chu_hogiadinh_so_dien_thoai'),
        ('nhan_khau', '0002_biendongnhankhau'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hogiadinh',
            old_name='duong_pho',
            new_name='dia_chi',
        ),
        migrations.RemoveField(
            model_name='hogiadinh',
            name='quan_huyen',
        ),
        migrations.RemoveField(
            model_name='hogiadinh',
            name='so_nha',
        ),
        migrations.AddField(
            model_name='hogiadinh',
            name='id_chu_ho',
            field=models.OneToOneField(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chu_ho_cua', to='nhan_khau.nhankhau'),
        ),
    ]
