# Generated by Django 5.2.7 on 2025-12-15 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ho_gia_dinh', '0003_rename_duong_pho_hogiadinh_dia_chi_and_more'),
        ('nhan_khau', '0008_rename_ngay_thay_doi_biendongnhankhau_thoi_gian_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hogiadinh',
            name='id_chu_ho',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chu_ho_cua', to='nhan_khau.nhankhau'),
        ),
    ]
