# Generated by Django 5.2.7 on 2025-11-03 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ho_gia_dinh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LichSinhHoat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chu_de', models.CharField(max_length=255)),
                ('ngay_to_chuc', models.DateField()),
                ('gio_to_chuc', models.TimeField()),
                ('dia_diem', models.CharField(max_length=255)),
                ('noi_dung', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThamGiaSinhHoat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('da_tham_gia', models.BooleanField(default=False)),
                ('ho_gia_dinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ho_gia_dinh.hogiadinh')),
                ('lich_sinh_hoat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sinh_hoat.lichsinhhoat')),
            ],
        ),
    ]
