# Generated by Django 5.2.7 on 2025-11-03 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('can_bo', '0003_alter_canbo_ngay_nhan_chuc'),
        ('sinh_hoat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichsinhhoat',
            name='ghi_chu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lichsinhhoat',
            name='nguoi_tao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='can_bo.canbo'),
        ),
    ]
