# Generated by Django 5.2.4 on 2025-12-26 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ho_gia_dinh', '0004_alter_hogiadinh_id_chu_ho'),
        ('sinh_hoat', '0002_lichsinhhoat_ghi_chu_lichsinhhoat_nguoi_tao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lichsinhhoat',
            options={'ordering': ['-ngay_to_chuc', '-gio_to_chuc']},
        ),
        migrations.AddField(
            model_name='lichsinhhoat',
            name='trang_thai',
            field=models.CharField(choices=[('chua_dien_ra', 'Chưa diễn ra'), ('dang_dien_ra', 'Đang diễn ra'), ('da_ket_thuc', 'Đã kết thúc')], default='chua_dien_ra', max_length=20),
        ),
        migrations.AddField(
            model_name='lichsinhhoat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='thamgiasinhhoat',
            name='ngay_tham_gia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thamgiasinhhoat',
            name='ho_gia_dinh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tham_gia_hoat_dong', to='ho_gia_dinh.hogiadinh'),
        ),
        migrations.AlterField(
            model_name='thamgiasinhhoat',
            name='lich_sinh_hoat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_sach_tham_gia', to='sinh_hoat.lichsinhhoat'),
        ),
        migrations.AlterUniqueTogether(
            name='thamgiasinhhoat',
            unique_together={('ho_gia_dinh', 'lich_sinh_hoat')},
        ),
        migrations.CreateModel(
            name='ChungChiGiaDinhVanHoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.IntegerField(choices=[(2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029')])),
                ('so_lan_tham_gia', models.IntegerField(default=0)),
                ('tieu_chi_tham_gia', models.IntegerField(default=0, help_text='Số lần tham gia yêu cầu')),
                ('dat_chuan', models.BooleanField(default=False)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('ngay_cap', models.DateTimeField(auto_now_add=True)),
                ('ngay_sua', models.DateTimeField(auto_now=True)),
                ('ho_gia_dinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chung_chi_gia_dinh_van_hoa', to='ho_gia_dinh.hogiadinh')),
            ],
            options={
                'ordering': ['-nam'],
                'unique_together': {('ho_gia_dinh', 'nam')},
            },
        ),
        migrations.CreateModel(
            name='ThuMoiSinhHoat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trang_thai', models.CharField(choices=[('chua_gui', 'Chưa gửi'), ('da_gui', 'Đã gửi'), ('da_xem', 'Đã xem'), ('da_phan_hoi', 'Đã phản hồi')], default='chua_gui', max_length=20)),
                ('ngay_gui', models.DateTimeField(auto_now_add=True)),
                ('ngay_xem', models.DateTimeField(blank=True, null=True)),
                ('phan_hoi_tham_gia', models.BooleanField(blank=True, null=True)),
                ('ngay_phan_hoi', models.DateTimeField(blank=True, null=True)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('ho_gia_dinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thu_moi_sinh_hoat', to='ho_gia_dinh.hogiadinh')),
                ('lich_sinh_hoat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_sach_thu_moi', to='sinh_hoat.lichsinhhoat')),
            ],
            options={
                'ordering': ['-ngay_gui'],
                'unique_together': {('lich_sinh_hoat', 'ho_gia_dinh')},
            },
        ),
    ]
