# Generated by Django 5.2.7 on 2025-12-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinh_hoat', '0003_alter_lichsinhhoat_options_lichsinhhoat_trang_thai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chungchigiadinhvanhoa',
            name='tong_so_buoi_sinh_hoat',
            field=models.IntegerField(default=0, help_text='Tổng số buổi sinh hoạt trong năm'),
        ),
        migrations.AlterField(
            model_name='chungchigiadinhvanhoa',
            name='tieu_chi_tham_gia',
            field=models.IntegerField(default=80, help_text='Tỷ lệ tham gia tối thiểu (%)'),
        ),
    ]
