# Generated by Django 5.2.7 on 2025-11-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tai_khoan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taikhoan',
            name='role',
            field=models.CharField(choices=[('can_bo', 'Cán bộ'), ('nguoi_dan', 'Người dân')], default='nguoi_dan', max_length=20),
        ),
        migrations.AlterField(
            model_name='taikhoan',
            name='chuc_vu',
            field=models.CharField(blank=True, choices=[('to_truong', 'Tổ trưởng'), ('to_pho', 'Tổ phó'), ('can_bo', 'Cán bộ')], max_length=20, null=True),
        ),
    ]
