# Generated by Django 5.2.7 on 2025-12-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tai_khoan', '0002_taikhoan_role_alter_taikhoan_chuc_vu'),
    ]

    operations = [
        migrations.AddField(
            model_name='taikhoan',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
