# Generated by Django 5.2.7 on 2025-12-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tai_khoan', '0003_taikhoan_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='taikhoan',
            name='cccd',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Số CCCD'),
        ),
    ]
