# Generated by Django 5.2.4 on 2025-12-22 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhan_khau', '0010_ensure_ngay_chuyen_noi_chuyen'),
        ('tai_khoan', '0004_taikhoan_cccd'),
    ]

    operations = [
        migrations.AddField(
            model_name='taikhoan',
            name='nhan_khau',
            field=models.OneToOneField(blank=True, help_text='Liên kết thông tin nhân khẩu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tai_khoan', to='nhan_khau.nhankhau'),
        ),
        migrations.AlterField(
            model_name='taikhoan',
            name='cccd',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Số CCCD'),
        ),
    ]
