# Generated by Django 5.2.7 on 2025-12-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tai_khoan', '0005_taikhoan_nhan_khau_alter_taikhoan_cccd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taikhoan',
            name='nhan_khau',
        ),
        migrations.AlterField(
            model_name='taikhoan',
            name='cccd',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Số CCCD'),
        ),
    ]
