# Generated by Django 5.2.7 on 2025-12-23 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhan_khau', '0010_remove_nhankhau_ngay_chuyen_di_and_more'),
        ('tai_khoan', '0006_remove_taikhoan_nhan_khau_alter_taikhoan_cccd'),
    ]

    operations = [
        migrations.AddField(
            model_name='taikhoan',
            name='nhan_khau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tai_khoan', to='nhan_khau.nhankhau', verbose_name='Nhân khẩu'),
        ),
    ]
