# Generated by Django 5.2.7 on 2025-11-04 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tai_khoan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThongKeNhanKhau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_thong_ke', models.DateTimeField(auto_now_add=True)),
                ('tong_nhan_khau', models.PositiveIntegerField(default=0)),
                ('so_nam', models.PositiveIntegerField(default=0)),
                ('so_nu', models.PositiveIntegerField(default=0)),
                ('mam_non', models.PositiveIntegerField(default=0)),
                ('mau_giao', models.PositiveIntegerField(default=0)),
                ('cap_1', models.PositiveIntegerField(default=0)),
                ('cap_2', models.PositiveIntegerField(default=0)),
                ('cap_3', models.PositiveIntegerField(default=0)),
                ('lao_dong', models.PositiveIntegerField(default=0)),
                ('nghi_huu', models.PositiveIntegerField(default=0)),
                ('tam_tru', models.PositiveIntegerField(default=0)),
                ('tam_vang', models.PositiveIntegerField(default=0)),
                ('tu_ngay', models.DateField(blank=True, null=True)),
                ('den_ngay', models.DateField(blank=True, null=True)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('NGUOI_TAO', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tai_khoan.taikhoan')),
            ],
            options={
                'verbose_name': 'Thống kê nhân khẩu',
                'verbose_name_plural': 'Các bản thống kê nhân khẩu',
            },
        ),
    ]
