# Generated by Django 5.2.7 on 2025-11-04 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thong_ke', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thongkenhankhau',
            old_name='NGUOI_TAO',
            new_name='nguoi_tao',
        ),
    ]
