# Generated by Django 5.2.7 on 2025-11-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanBo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chuc_danh', models.CharField(max_length=100)),
                ('so_dien_thoai', models.CharField(max_length=15)),
                ('nhiem_vu_phu_trach', models.CharField(max_length=100)),
                ('ngay_nhan_chuc', models.DateField()),
            ],
        ),
    ]
