# Generated by Django 5.2.7 on 2025-11-01 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('can_bo', '0001_initial'),
        ('tai_khoan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canbo',
            name='tai_khoan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tai_khoan.taikhoan'),
        ),
    ]
