# Generated by Django 5.2.7 on 2025-11-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('can_bo', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canbo',
            name='ngay_nhan_chuc',
            field=models.DateField(blank=True, null=True),
        ),
    ]
