# Generated by Django 5.2.7 on 2025-11-01 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nhan_khau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhieuTamTruTamVang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_phieu', models.CharField(choices=[('tam_tru', 'Tạm trú'), ('tam_vang', 'Tạm vắng')], max_length=10)),
                ('ngay_bat_dau', models.DateField()),
                ('ngay_ket_thuc', models.DateField(blank=True, null=True)),
                ('ly_do', models.TextField()),
                ('dia_chi_tam_tru', models.CharField(blank=True, max_length=255, null=True)),
                ('nhan_khau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhan_khau.nhankhau')),
            ],
        ),
    ]
