# Generated by Django 5.2.7 on 2025-11-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tam_tru_tam_vang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phieutamtrutamvang',
            name='ghi_chu',
            field=models.TextField(blank=True, null=True),
        ),
    ]
