# Generated by Django 5.2.7 on 2025-12-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tam_tru_tam_vang', '0002_phieutamtrutamvang_ghi_chu'),
    ]

    operations = [
        migrations.AddField(
            model_name='phieutamtrutamvang',
            name='trang_thai',
            field=models.CharField(choices=[('cho_duyet', 'Chưa duyệt'), ('da_duyet', 'Đã duyệt')], default='cho_duyet', max_length=20),
        ),
    ]
