# Generated by Django 5.2.7 on 2025-12-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tam_tru_tam_vang', '0003_phieutamtrutamvang_trang_thai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phieutamtrutamvang',
            name='trang_thai',
            field=models.CharField(choices=[('cho_duyet', 'Chưa duyệt'), ('da_duyet', 'Đã duyệt'), ('tu_choi', 'Từ chối')], default='cho_duyet', max_length=20),
        ),
    ]
