# Generated by Django 5.2.4 on 2025-12-31 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tam_tru_tam_vang', '0002_phieutamtrutamvang_created_at_and_more'),
        ('tam_tru_tam_vang', '0004_alter_phieutamtrutamvang_trang_thai'),
    ]

    operations = [
    ]
