# Generated by Django 5.2.7 on 2025-11-01 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ho_gia_dinh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhanKhau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100)),
                ('bi_danh', models.CharField(blank=True, max_length=50, null=True)),
                ('ngay_sinh', models.DateField()),
                ('noi_sinh', models.CharField(max_length=100)),
                ('nguyen_quan', models.CharField(max_length=100)),
                ('dan_toc', models.CharField(max_length=50)),
                ('nghe_nghiep', models.CharField(blank=True, max_length=100, null=True)),
                ('noi_lam_viec', models.CharField(blank=True, max_length=150, null=True)),
                ('so_cccd', models.CharField(blank=True, max_length=20, null=True)),
                ('ngay_cap', models.DateField(blank=True, null=True)),
                ('noi_cap', models.CharField(blank=True, max_length=100, null=True)),
                ('quan_he_voi_chu_ho', models.CharField(max_length=50)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('ho_gia_dinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nhan_khau', to='ho_gia_dinh.hogiadinh')),
            ],
        ),
    ]
