# Generated by Django 5.2.7 on 2025-11-03 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('can_bo', '0003_alter_canbo_ngay_nhan_chuc'),
        ('nhan_khau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BienDongNhanKhau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_bien_dong', models.CharField(choices=[('TAO_MOI', 'Thêm nhân khẩu'), ('XOA', 'Xóa nhân khẩu'), ('TACH_HO', 'Tách hộ'), ('NHAP_HO', 'Nhập hộ'), ('TAM_VANG', 'Tạm vắng'), ('TAM_TRU', 'Tạm trú'), ('CHUYEN_KHAU', 'Chuyển khẩu')], max_length=20)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('ngay_thay_doi', models.DateTimeField(auto_now_add=True)),
                ('can_bo_thuc_hien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='can_bo.canbo')),
                ('nhan_khau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_bien_dong', to='nhan_khau.nhankhau')),
            ],
        ),
    ]
