# Generated by Django 5.2.7 on 2025-11-04 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('can_bo', '0003_alter_canbo_ngay_nhan_chuc'),
        ('ho_gia_dinh', '0003_rename_duong_pho_hogiadinh_dia_chi_and_more'),
        ('nhan_khau', '0002_biendongnhankhau'),
    ]

    operations = [
        migrations.AddField(
            model_name='biendongnhankhau',
            name='ho_khau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bien_dong_ho_khau', to='ho_gia_dinh.hogiadinh'),
        ),
        migrations.AddField(
            model_name='nhankhau',
            name='dia_chi_thuong_tru_truoc_day',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nhankhau',
            name='gioi_tinh',
            field=models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], default='Nam', max_length=5),
        ),
        migrations.AddField(
            model_name='nhankhau',
            name='thoi_gian_dang_ki_thuong_tru',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nhankhau',
            name='trang_thai',
            field=models.CharField(choices=[('song', 'còn sống'), ('chet', 'đã chết'), ('chuyen_di', 'Đã chuyển đi')], default='song', max_length=20),
        ),
        migrations.AlterField(
            model_name='biendongnhankhau',
            name='can_bo_thuc_hien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thay_doi_bien_dong', to='can_bo.canbo'),
        ),
        migrations.AlterField(
            model_name='biendongnhankhau',
            name='loai_bien_dong',
            field=models.CharField(choices=[('TAO_MOI', 'Thêm nhân khẩu'), ('CAP_NHAT', 'Cập nhật thông tin'), ('XOA', 'Xóa nhân khẩu'), ('TACH_HO', 'Tách hộ'), ('NHAP_HO', 'Nhập hộ'), ('TAM_VANG', 'Tạm vắng'), ('TAM_TRU', 'Tạm trú'), ('CHUYEN_KHAU', 'Chuyển khẩu')], max_length=20),
        ),
        migrations.AlterField(
            model_name='biendongnhankhau',
            name='nhan_khau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bien_dong_nhan_khau', to='nhan_khau.nhankhau'),
        ),
    ]
