# Generated by Django 5.2.7 on 2025-11-25 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('can_bo', '0003_alter_canbo_ngay_nhan_chuc'),
        ('ho_gia_dinh', '0003_rename_duong_pho_hogiadinh_dia_chi_and_more'),
        ('nhan_khau', '0003_biendongnhankhau_ho_khau_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhankhau',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='nhankhau',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='biendongnhankhau',
            name='loai_bien_dong',
            field=models.CharField(choices=[('TAO_MOI', 'Thêm nhân khẩu'), ('CAP_NHAT', 'Cập nhật thông tin'), ('XOA', 'Xóa nhân khẩu'), ('KHAI_TU', 'Khai tử'), ('TACH_HO', 'Tách hộ'), ('NHAP_HO', 'Nhập hộ'), ('TAM_VANG', 'Tạm vắng'), ('TAM_TRU', 'Tạm trú'), ('CHUYEN_KHAU', 'Chuyển khẩu')], max_length=20),
        ),
        migrations.AlterField(
            model_name='nhankhau',
            name='ho_gia_dinh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhan_khau', to='ho_gia_dinh.hogiadinh'),
        ),
        migrations.AlterField(
            model_name='nhankhau',
            name='so_cccd',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='nhankhau',
            name='trang_thai',
            field=models.CharField(choices=[('song', 'còn sống'), ('chet', 'đã chết'), ('tam_tru', 'tạm trú'), ('tam_vang', 'tạm vắng'), ('chuyen_di', 'Đã chuyển đi')], default='song', max_length=20),
        ),
        migrations.CreateModel(
            name='TamTru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_giay_tam_tru', models.CharField(max_length=20, unique=True)),
                ('so_dien_thoai_nguoi_dang_ky', models.CharField(blank=True, max_length=15, null=True)),
                ('tu_ngay', models.DateField()),
                ('den_ngay', models.DateField()),
                ('ly_do', models.TextField(blank=True, null=True)),
                ('dia_chi_tam_tru', models.CharField(help_text='Địa chỉ nơi đang tạm trú', max_length=200)),
                ('ngay_dang_ky', models.DateTimeField(auto_now_add=True)),
                ('can_bo_cap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='can_bo.canbo')),
                ('nhan_khau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_tam_tru', to='nhan_khau.nhankhau')),
            ],
        ),
        migrations.CreateModel(
            name='TamVang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_giay_tam_vang', models.CharField(max_length=20, unique=True)),
                ('noi_tam_tru', models.CharField(max_length=200)),
                ('tu_ngay', models.DateField()),
                ('den_ngay', models.DateField()),
                ('ly_do', models.TextField(blank=True, null=True)),
                ('ngay_dang_ky', models.DateTimeField(auto_now_add=True)),
                ('can_bo_cap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='can_bo.canbo')),
                ('nhan_khau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_tam_vang', to='nhan_khau.nhankhau')),
            ],
        ),
    ]
