# Generated by Django 5.2.4 on 2025-12-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhan_khau', '0004_nhankhau_created_at_nhankhau_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhankhau',
            name='ngay_xoa',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
