# Generated by Django 5.2.4 on 2025-12-14 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhan_khau', '0005_nhankhau_ngay_xoa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nhankhau',
            name='ngay_xoa',
        ),
    ]
