# Generated by Django 5.2.4 on 2025-12-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhan_khau', '0006_remove_nhankhau_ngay_xoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhankhau',
            name='ngay_chuyen_di',
            field=models.DateField(blank=True, help_text="Ngày chuyển đi (chỉ khi trạng thái là 'Đã chuyển đi')", null=True),
        ),
        migrations.AddField(
            model_name='nhankhau',
            name='noi_chuyen',
            field=models.CharField(blank=True, help_text="Nơi chuyển tới (chỉ khi trạng thái là 'Đã chuyển đi')", max_length=255, null=True),
        ),
    ]
