# Generated by Django 5.2.7 on 2025-12-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhan_khau', '0007_nhankhau_ngay_chuyen_di_nhankhau_noi_chuyen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biendongnhankhau',
            old_name='ngay_thay_doi',
            new_name='thoi_gian',
        ),
        migrations.RemoveField(
            model_name='biendongnhankhau',
            name='can_bo_thuc_hien',
        ),
        migrations.AlterField(
            model_name='biendongnhankhau',
            name='loai_bien_dong',
            field=models.CharField(choices=[('THAY_DOI_CHU_HO', 'Thay đổi chủ hộ'), ('MOI_SINH', 'Mới sinh'), ('CHUYEN_DEN', 'Chuyển đến (Nhập hộ)'), ('CHUYEN_DI', 'Chuyển đi nơi khác'), ('KHAI_TU', 'Khai tử'), ('TACH_HO', 'Tách hộ'), ('TAM_VANG', 'Khai báo tạm vắng'), ('TAM_TRU', 'Đăng ký tạm trú')], max_length=20),
        ),
        migrations.AlterField(
            model_name='nhankhau',
            name='trang_thai',
            field=models.CharField(choices=[('thuong_tru', 'Thường trú'), ('tam_tru', 'Tạm trú'), ('tam_vang', 'Tạm vắng'), ('chuyen_di', 'Đã chuyển đi'), ('da_chet', 'Đã qua đời')], default='thuong_tru', max_length=20),
        ),
    ]
