# Generated by Django 5.2.7 on 2025-12-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhan_khau', '0008_rename_ngay_thay_doi_biendongnhankhau_thoi_gian_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhankhau',
            name='ngay_chuyen_di',
            field=models.DateField(blank=True, help_text='Ngày chuyển đi ', null=True),
        ),
        migrations.AlterField(
            model_name='nhankhau',
            name='noi_chuyen',
            field=models.CharField(blank=True, help_text='Nơi chuyển tới ', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nhankhau',
            name='quan_he_voi_chu_ho',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
