# Generated by Django 5.2.4 on 2025-12-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhan_khau', '0009_alter_nhankhau_ngay_chuyen_di_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nhankhau',
            name='ngay_chuyen_di',
        ),
        migrations.RemoveField(
            model_name='nhankhau',
            name='noi_chuyen',
        ),
        migrations.AddField(
            model_name='biendongnhankhau',
            name='ngay_bat_dau',
            field=models.DateField(blank=True, help_text='Ngày sự kiện (Bắt buộc cho tạm trú, tạm vắng, mới sinh, khai tử, chuyển đi)', null=True, verbose_name='Ngày bắt đầu'),
        ),
        migrations.AddField(
            model_name='biendongnhankhau',
            name='ngay_chuyen_di',
            field=models.DateField(blank=True, help_text='Ngày chuyển đi (Dùng khi có cụ thể ngày khác so với ngay_bat_dau)', null=True, verbose_name='Ngày chuyển đi'),
        ),
        migrations.AddField(
            model_name='biendongnhankhau',
            name='ngay_ket_thuc',
            field=models.DateField(blank=True, help_text='Ngày kết thúc (Chỉ áp dụng cho tạm trú, tạm vắng)', null=True, verbose_name='Ngày kết thúc'),
        ),
        migrations.AddField(
            model_name='biendongnhankhau',
            name='noi_chuyen',
            field=models.CharField(blank=True, help_text='Địa chỉ nơi chuyển đi hoặc nơi chuyển đến từ', max_length=255, null=True, verbose_name='Nơi chuyển tới'),
        ),
    ]
