# Generated by Django 5.2.7 on 2025-12-29 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhan_khau', '0010_remove_nhankhau_ngay_chuyen_di_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaoCaiThongTin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_bat_dau', models.DateField()),
                ('ly_do', models.TextField(help_text='Mô tả chi tiết thông tin sai')),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('trang_thai', models.CharField(choices=[('cho_duyet', 'Chờ duyệt'), ('da_duyet', 'Đã duyệt'), ('tu_choi', 'Từ chối')], default='cho_duyet', max_length=20)),
                ('truong_can_sua', models.CharField(blank=True, help_text='Tên trường cần sửa (ví dụ: ho_ten, ngay_sinh, so_cccd)', max_length=100, null=True)),
                ('gia_tri_cu', models.TextField(blank=True, null=True)),
                ('gia_tri_moi', models.TextField(help_text='Giá trị chính xác mà người dân báo cáo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nhan_khau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bao_sai_thong_tin', to='nhan_khau.nhankhau')),
            ],
        ),
    ]
