# Generated by Django 5.2.7 on 2025-12-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhan_khau', '0011_baocaithongtin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baocaithongtin',
            name='gia_tri_cu',
        ),
        migrations.RemoveField(
            model_name='baocaithongtin',
            name='gia_tri_moi',
        ),
        migrations.RemoveField(
            model_name='baocaithongtin',
            name='truong_can_sua',
        ),
        migrations.AddField(
            model_name='baocaithongtin',
            name='cac_truong_loi',
            field=models.JSONField(default=list, help_text='Array các trường cần sửa'),
        ),
        migrations.AlterField(
            model_name='baocaithongtin',
            name='ly_do',
            field=models.TextField(help_text='Mô tả chi tiết sai thông tin'),
        ),
    ]
