# Generated by Django 5.2.7 on 2025-12-29 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhan_khau', '0012_remove_baocaithongtin_gia_tri_cu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='XinCapGiayXacNhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_giay', models.CharField(choices=[('nhan_khau', 'Giấy xác nhận nhân khẩu'), ('ho_khau', 'Giấy xác nhận hộ khẩu'), ('muc_dich_khac', 'Mục đích khác')], default='nhan_khau', max_length=20)),
                ('so_luong', models.IntegerField(default=1)),
                ('ly_do', models.TextField()),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('trang_thai', models.CharField(choices=[('cho_duyet', 'Chờ duyệt'), ('da_duyet', 'Đã duyệt'), ('tu_choi', 'Từ chối')], default='cho_duyet', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nhan_khau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xin_cap_giay_xac_nhan', to='nhan_khau.nhankhau')),
            ],
        ),
    ]
